language: php

php:
    - 7.4

services:
    - rabbitmq-server

env:
    matrix:
        - COMPOSER_FLAGS="--prefer-lowest"
        - COMPOSER_FLAGS=""

before_script:
    - travis_retry composer self-update
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
    - composer run-script test-ci

after_script:
    - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
